import React, { createContext, useContext, useState, useRef } from "react";
import GlobalVariables from "../js/globalvariables.js";
import Molecule from "../molecules/molecule.js";
import { licenses } from "../js/licenseOptions.js";
import { re } from "mathjs";
import { useAuth } from "./AuthContext.jsx";
import { useAppState } from "./AppStateContext.jsx";
import { useNavigate } from "react-router-dom";

const ProjectContext = createContext();

/**
 * Context provider for project-level operations and state.
 * Centralizes project loading, saving, and CAD operations.
 */
export function ProjectProvider({ children, cad, loadProject }) {
  const [size, setSize] = useState(5);
  const { authorizedUserOcto, authRedirectHandler } = useAuth();
  const { setNotification } = useAppState();

  // Track last saved data to avoid unnecessary saves
  const lastSaveData = useRef({});

  var navigate = useNavigate();

  /**
   * The text to display at the top of the bill of materials.
   * @type {string}
   */
  var bomHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model \n# Bill Of Materials \n |Part|Number Needed|Price|Source| \n |----|----------|-----|-----|";
  /**
   * The text to display at the top of the ReadMe file.
   * @type {string}
   */
  var readmeHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model";

  /**
   * Create a new project or exports current molecule to github and navigate to new project create page
   * * @param {string} name - Project Name
   * @param {array} topics - Array of topics
   * @param {string} description - Project Description
   * @param {object} molecule - If there's an existing molecule to export
   * @param {boolean} exporting - If exporting a molecule
   *
   */
  const createProject = async (
    authorizedUserOcto,
    [name, topics, description, license, units],
    molecule,
    exporting,
    setNewProjectBar,
  ) => {
    let githubMoleculeUsedList = [];
    if (molecule !== undefined && exporting) {
      githubMoleculeUsedList = await searchGithubMolecules(
        GlobalVariables.topLevelMolecule,
      );
      GlobalVariables.topLevelMolecule = molecule;
      GlobalVariables.topLevelMolecule.enableAllChildren();
      molecule.topLevel = true;
      console.log("Exporting existing molecule as new project");
      console.log(GlobalVariables.topLevelMolecule);
    } else {
      GlobalVariables.topLevelMolecule = new Molecule({
        x: 0,
        y: 0,
        topLevel: true,
        name: name,
        atomType: "Molecule",
        uniqueID: GlobalVariables.generateUniqueID(),
        unitsKey: units,
      });
    }
    GlobalVariables.currentMolecule = GlobalVariables.topLevelMolecule;

    // Create the repo
    let result;
    let errors = [];
    try {
      result = await authorizedUserOcto.request("POST /user/repos", {
        name: name,
        description: description,
        headers: {
          "X-GitHub-Api-Version": "2022-11-28",
        },
      });
    } catch (err) {
      window.alert(
        "Error creating project. That name might be taken already. Please try again with a different name.",
      );
      return null;
    }
    setNewProjectBar(10);
    let currentRepoName = result.data.name;
    let currentUser = GlobalVariables.currentUser;

    // Check if the repo name was changed by GitHub
    if (currentRepoName !== name) {
      errors.push(
        `Project name was changed from "${name}" to "${currentRepoName}" to comply with GitHub requirements.`,
      );
    }

    // Update the top molecule name to match the project name
    if (GlobalVariables.topLevelMolecule) {
      GlobalVariables.topLevelMolecule.name = currentRepoName;
    }

    var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize();
    jsonRepOfProject.filetypeVersion = 1;
    const projectContent = window.btoa(
      GlobalVariables.toBinaryStr(JSON.stringify(jsonRepOfProject, null, 4)),
    );
    let topicString = topics.join(" ");
    let searchField = (
      result.data.name +
      " " +
      result.data.owner.login +
      " " +
      description +
      " " +
      topicString
    ).toLowerCase();
    let newProjectBody = {
      owner: result.data.owner.login,
      description: description,
      ranking: result.data.stargazers_count,
      searchField: searchField,
      repoName: result.data.name,
      forks: result.data.forks_count,
      topMoleculeID: GlobalVariables.topLevelMolecule.uniqueID,
      topics: topics,
      html_url: result.data.html_url,
      privateRepo: result.data.private,
      parentRepo: null,
      readme:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/README.md?sanitize=true",
      contentURL:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/project.abundance?sanitize=true",
      githubMoleculesUsed: githubMoleculeUsedList,
      svgURL:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/project.svg?sanitize=true",
      dateCreated: result.data.created_at,
    };

    // Post new project to AWS database
    const apiUrl =
      "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage//post-new-project";
    await fetch(apiUrl, {
      method: "POST",
      body: JSON.stringify(newProjectBody),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });
    GlobalVariables.currentAWSnode = newProjectBody;

    // Add to user table
    const apiUpdateUserUrl =
      "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/USER-TABLE";
    await fetch(apiUpdateUserUrl, {
      method: "POST",
      body: JSON.stringify({
        user: GlobalVariables.currentUser,
        attributeUpdates: { numProjectsOwned: 1 },
        updateType: "SET",
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });

    // Create the project files sequentially
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "project.abundance",
      message: "Initialize repo",
      content: projectContent,
    });
    setNewProjectBar(20);

    let content = window.btoa(bomHeader);
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "BillOfMaterials.md",
      message: "initialize BOM",
      content: content,
    });
    setNewProjectBar(30);

    content = window.btoa(readmeHeader);
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "README.md",
      message: "initialize README",
      content: content,
    });
    setNewProjectBar(40);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "project.svg",
      message: "SVG Picture",
      content: "",
    });
    setNewProjectBar(50);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: ".gitattributes",
      message: "Create gitattributes",
      content: window.btoa("data binary"),
    });
    setNewProjectBar(60);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "data.json",
      message: "Data file",
      content: "",
    });
    setNewProjectBar(80);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "LICENSE.txt",
      message: "Establish license",
      content: window.btoa(GlobalVariables.toBinaryStr(licenses[license])),
    });
    setNewProjectBar(90);

    // Set topics with error handling
    try {
      await authorizedUserOcto.rest.repos.replaceAllTopics({
        owner: currentUser,
        repo: currentRepoName,
        names: topics,
      });
    } catch (err) {
      console.error("Error setting topics:", err);
      errors.push(
        "Some project tags could not be added. GitHub requires tags to be lowercase, contain only letters, numbers, and hyphens, and be 50 characters or less.",
      );
    }

    // Display any errors or warnings to the user
    if (errors.length > 0) {
      window.alert(
        "Project created successfully!\n\nNote:\n" + errors.join("\n"),
      );
    }

    // All done, return the AWS node
    console.log("Project created");
    console.log(GlobalVariables.currentAWSnode);
    return GlobalVariables.currentAWSnode;
  };

  /** forkProject takes care of making the octokit request for the authenticated user to make a copy of a not owned repo */
  const forkProject = async function (
    authorizedUserOcto,
    setForkBarVisible,
    setForkProgress,
    setRedirectType,
  ) {
    var owner = GlobalVariables.currentAWSnode.owner;
    var repo = GlobalVariables.currentAWSnode.repoName;
    try {
      // if authenticated and it is not your project, make a clone of the project and return to create mode
      if (owner === GlobalVariables.currentUser) {
        // Prevent forking your own project
        console.warn("You cannot fork your own project.");
        navigate(
          `/${GlobalVariables.currentAWSnode.owner}/${GlobalVariables.currentAWSnode.repoName}`,
        );
        return;
      }

      setForkBarVisible(true);
      setForkProgress(0);

      // Get the original repo info
      const result = await authorizedUserOcto.request(
        "GET /repos/{owner}/{repo}",
        {
          owner: owner,
          repo: repo,
        },
      );
      setForkProgress(5);

      // Create the fork
      await authorizedUserOcto.rest.repos.createFork({
        owner: owner,
        repo: repo,
      });
      setForkProgress(50);

      // Prepare AWS node body
      const apiUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage//post-new-project";
      let searchField = (
        result.data.name +
        " " +
        GlobalVariables.currentUser
      ).toLowerCase();
      let forkedNodeBody = {
        owner: GlobalVariables.currentUser,
        ranking: result.data.stargazers_count,
        description: result.data.description,
        searchField: searchField,
        repoName: result.data.name,
        forks: 0,
        topMoleculeID: GlobalVariables.topLevelMolecule.uniqueID,
        topics: [],
        readme:
          "https://raw.githubusercontent.com/" +
          GlobalVariables.currentUser +
          "/" +
          result.data.name +
          "/master/README.md?sanitize=true",
        contentURL:
          "https://raw.githubusercontent.com/" +
          GlobalVariables.currentUser +
          "/" +
          result.data.name +
          "/master/project.abundance?sanitize=true",
        githubMoleculesUsed: [],
        parentRepo: owner + "/" + repo,
        svgURL:
          "https://raw.githubusercontent.com/" +
          GlobalVariables.currentUser +
          "/" +
          result.data.name +
          "/master/project.svg?sanitize=true",
        dateCreated: result.data.created_at,
        html_url:
          "https://github.com/" +
          GlobalVariables.currentUser +
          "/" +
          result.data.name,
      };

      // Post to AWS
      setForkProgress(75);
      const response = await fetch(apiUrl, {
        method: "POST",
        body: JSON.stringify(forkedNodeBody),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });
      setForkProgress(100);

      GlobalVariables.currentAWSnode = forkedNodeBody;
      setRedirectType(null);

      // Hide progress bar after a short delay
      setTimeout(() => {
        setForkBarVisible(false);
      }, 1000);

      navigate(
        `/${GlobalVariables.currentUser}/${GlobalVariables.currentAWSnode.repoName}`,
        { replace: true },
      );
    } catch (error) {
      console.error("Error during forking the repository:", error);
      setNotification(
        error?.message || "Error forking the repository. Please try again.",
      );
      // Hide progress bar after a short delay
      setTimeout(() => {
        setForkBarVisible(false);
      }, 1000);

      setRedirectType && setRedirectType(null);
    }
  };

  const searchGithubMolecules = (molecule) => {
    return new Promise((resolve, reject) => {
      try {
        const githubMoleculeUsedList = [];

        function recursiveSearch(molecule) {
          // Check if the molecule has nodes
          if (
            !molecule.nodesOnTheScreen ||
            !Array.isArray(molecule.nodesOnTheScreen)
          ) {
            return;
          }
          // Iterate through each node in the molecule
          molecule.nodesOnTheScreen.forEach((node) => {
            if (node.atomType === "GitHubMolecule") {
              // Add to the githubMoleculeUsedList if atomType is "Github molecule"
              if (node.parentRepo == null) return; // Safety check if parentRepo is null
              githubMoleculeUsedList.push({
                owner: node.parentRepo.owner,
                repoName: node.parentRepo.repoName,
              });
            } else if (node.atomType === "Molecule") {
              // Recursively search inside the nodes of this molecule
              recursiveSearch(node);
            }
          });
        }

        // Start the recursive search
        recursiveSearch(molecule);

        // Resolve the promise with the list of Github molecules
        resolve(githubMoleculeUsedList);
      } catch (error) {
        // Reject the promise if an error occurs
        reject(error);
      }
    });
  };

  /**
   * Duplicate the current project by creating a new repository
   * @param {object} authorizedUserOcto - Authenticated Octokit instance
   * @param {function} setDuplicateProjectBar - Progress bar callback
   * @param {string} customName - Custom name for the duplicated project (optional)
   * @param {function} setErrorNotification - Callback to set error notification message
   * @returns {object} The new project AWS node or null on error
   */
  const duplicateProject = async (
    authorizedUserOcto,
    setDuplicateProjectBar,
    customName = null,
  ) => {
    console.log("Duplicating project...");
    console.log(GlobalVariables.currentRepo);
    try {
      const currentRepo = GlobalVariables.currentRepo;
      const currentUser = GlobalVariables.currentUser;

      if (!currentRepo || !currentUser) {
        window.alert(
          "Cannot duplicate project: No active project or user not authenticated.",
        );
        return null;
      }

      // Use custom name or generate new project name with "-copy" suffix
      let newRepoName = customName || currentRepo.name + "-copy";

      // Check if name already exists and increment if needed (only if using default name)
      if (!customName) {
        let nameExists = true;
        let counter = 1;
        while (nameExists) {
          try {
            await authorizedUserOcto.request("GET /repos/{owner}/{repo}", {
              owner: currentUser,
              repo: newRepoName,
            });
            // If we get here, repo exists, so try with a counter
            newRepoName = currentRepo.name + "-copy-" + counter;
            counter++;
          } catch (err) {
            // 404 means repo doesn't exist, so we can use this name
            if (err.status === 404) {
              nameExists = false;
            } else {
              throw err;
            }
          }
        }
      }

      setDuplicateProjectBar(5);

      // Create the new repository
      let newRepo;
      try {
        newRepo = await authorizedUserOcto.request("POST /user/repos", {
          name: newRepoName,
          description: currentRepo.description || "",
          headers: {
            "X-GitHub-Api-Version": "2022-11-28",
          },
        });
      } catch (err) {
        window.alert("Error creating duplicate project. Please try again.");
        return null;
      }

      setDuplicateProjectBar(10);

      // Get all files from the current repository
      const filesToCopy = [
        "project.abundance",
        "BillOfMaterials.md",
        "README.md",
        "project.svg",
        ".gitattributes",
        "data.json",
        "LICENSE.txt",
      ];

      let copiedFiles = 0;
      const totalFiles = filesToCopy.length;

      // Copy each file from the original repo to the new repo
      for (const filePath of filesToCopy) {
        try {
          // Get file content from current repo
          const fileResponse = await authorizedUserOcto.request(
            "GET /repos/{owner}/{repo}/contents/{path}",
            {
              owner: currentRepo.owner.login,
              repo: currentRepo.name,
              path: filePath,
            },
          );

          let fileContent;
          if (
            !fileResponse.data.content ||
            fileResponse.data.content.length === 0
          ) {
            // Handle large files using download_url
            const contentResponse = await fetch(fileResponse.data.download_url);
            const rawContent = await contentResponse.text();
            fileContent = window.btoa(GlobalVariables.toBinaryStr(rawContent));
          } else {
            // Use the base64 content directly
            fileContent = fileResponse.data.content.replace(/\n/g, "");
          }

          // Create file in new repo
          await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
            owner: currentUser,
            repo: newRepo.data.name,
            path: filePath,
            message: `Copy ${filePath} from ${currentRepo.name}`,
            content: fileContent,
          });

          copiedFiles++;
          const progress = 10 + Math.floor((copiedFiles / totalFiles) * 70);
          setDuplicateProjectBar(progress);
        } catch (err) {
          console.error(`Error copying file ${filePath}:`, err);
          // Continue with other files even if one fails
        }
      }

      setDuplicateProjectBar(85);

      // Update the top molecule name in project.abundance to match the new project name
      try {
        // Get the current project.abundance file from the new repo
        const projectFileResponse = await authorizedUserOcto.request(
          "GET /repos/{owner}/{repo}/contents/{path}",
          {
            owner: currentUser,
            repo: newRepo.data.name,
            path: "project.abundance",
          },
        );

        let projectFileContent;
        if (
          !projectFileResponse.data.content ||
          projectFileResponse.data.content.length === 0
        ) {
          // Handle large files using download_url
          const contentResponse = await fetch(
            projectFileResponse.data.download_url,
          );
          projectFileContent = await contentResponse.text();
        } else {
          // Decode base64 content
          projectFileContent = GlobalVariables.fromBinaryStr(
            atob(projectFileResponse.data.content),
          );
        }

        // Parse the JSON
        const projectData = JSON.parse(projectFileContent);

        // Update the top molecule name to match the new project name
        if (projectData && projectData.name) {
          projectData.name = newRepo.data.name;
        }

        // Convert back to base64
        const updatedContent = window.btoa(
          GlobalVariables.toBinaryStr(JSON.stringify(projectData, null, 4)),
        );

        // Update the file in the new repo
        await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
          owner: currentUser,
          repo: newRepo.data.name,
          path: "project.abundance",
          message: `Update top molecule name to ${newRepo.data.name}`,
          content: updatedContent,
          sha: projectFileResponse.data.sha,
        });

        console.log(
          `Updated top molecule name to ${newRepo.data.name} in duplicated project`,
        );
      } catch (err) {
        console.error("Error updating top molecule name:", err);
        // Continue even if this fails - project is still functional
      }

      setDuplicateProjectBar(90);

      // Copy topics if they exist
      if (currentRepo.topics && currentRepo.topics.length > 0) {
        try {
          await authorizedUserOcto.rest.repos.replaceAllTopics({
            owner: currentUser,
            repo: newRepo.data.name,
            names: currentRepo.topics,
          });
        } catch (err) {
          console.error("Error copying topics:", err);
        }
      }

      setDuplicateProjectBar(93);

      // Ensure GlobalVariables.topLevelMolecule is up to date by loading the duplicated project.abundance
      try {
        const projectFileResponse = await authorizedUserOcto.request(
          "GET /repos/{owner}/{repo}/contents/{path}",
          {
            owner: currentUser,
            repo: newRepo.data.name,
            path: "project.abundance",
          },
        );
        let projectFileContent;
        if (
          !projectFileResponse.data.content ||
          projectFileResponse.data.content.length === 0
        ) {
          const contentResponse = await fetch(
            projectFileResponse.data.download_url,
          );
          projectFileContent = await contentResponse.text();
        } else {
          projectFileContent = GlobalVariables.fromBinaryStr(
            atob(projectFileResponse.data.content),
          );
        }
        // Parse and update topLevelMolecule
        const projectData = JSON.parse(projectFileContent);
        GlobalVariables.topLevelMolecule = new Molecule(projectData);
      } catch (err) {
        console.error(
          "Error updating GlobalVariables.topLevelMolecule for AWS node:",
          err,
        );
      }

      // Populate githubMoleculesUsed using searchGithubMolecules
      let githubMoleculeUsedList = [];
      try {
        githubMoleculeUsedList = await searchGithubMolecules(
          GlobalVariables.topLevelMolecule,
        );
      } catch (err) {
        console.error("Error searching GitHub molecules for AWS node:", err);
      }

      // Create AWS node for the new project
      const newProjectBody = {
        owner: currentUser,
        description: newRepo.data.description || "",
        ranking: 0,
        searchField: (
          newRepo.data.name +
          " " +
          currentUser +
          " " +
          (newRepo.data.description || "")
        ).toLowerCase(),
        repoName: newRepo.data.name,
        forks: 0,
        topMoleculeID: GlobalVariables.topLevelMolecule?.uniqueID || "",
        topics: currentRepo.topics || [],
        html_url: newRepo.data.html_url,
        parentRepo: null,
        readme:
          "https://raw.githubusercontent.com/" +
          newRepo.data.full_name +
          "/master/README.md?sanitize=true",
        contentURL:
          "https://raw.githubusercontent.com/" +
          newRepo.data.full_name +
          "/master/project.abundance?sanitize=true",
        githubMoleculesUsed: githubMoleculeUsedList,
        svgURL:
          "https://raw.githubusercontent.com/" +
          newRepo.data.full_name +
          "/master/project.svg?sanitize=true",
        dateCreated: newRepo.data.created_at,
      };

      // Post new project to AWS database
      const apiUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/post-new-project";
      const postProjectResponse = await fetch(apiUrl, {
        method: "POST",
        body: JSON.stringify(newProjectBody),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });
      console.log("Posted new project to AWS:", postProjectResponse);
      if (postProjectResponse.status !== 200) {
        throw new Error(
          `Failed to post new project: ${postProjectResponse.status}`,
        );
      }

      // Update user table
      const apiUpdateUserUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/USER-TABLE";
      const updateUserResponse = await fetch(apiUpdateUserUrl, {
        method: "POST",
        body: JSON.stringify({
          user: currentUser,
          attributeUpdates: { numProjectsOwned: 1 },
          updateType: "SET",
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });
      if (!updateUserResponse.ok) {
        throw new Error(
          `Failed to update user table: ${updateUserResponse.status}`,
        );
      }

      setDuplicateProjectBar(100);

      return newProjectBody;
    } catch (err) {
      console.error("Error duplicating project:", err);
      setNotification("Error duplicating project. Please try again.", "error");

      return null;
    }
  };

  /**
   * Rename an existing project by updating GitHub repository and AWS entry
   * @param {object} authorizedUserOcto - Authenticated Octokit instance
   * @param {string} newName - New name for the project
   * @param {function} setRenameProgress - Progress callback (0-100)
   * @returns {object|null} Updated AWS node or null on error
   */
  const renameProject = async (
    authorizedUserOcto,
    newName,
    setRenameProgress = () => {},
  ) => {
    console.log(GlobalVariables.currentRepo);
    try {
      const currentUser = GlobalVariables.currentUser;
      const currentAWSnode = GlobalVariables.currentAWSnode;
      const oldRepoName = currentAWSnode.repoName;
      const oldOwner = currentAWSnode.owner;

      if (!authorizedUserOcto || !currentUser) {
        window.alert("Missing required data for renaming project.");
        return null;
      }

      // Check if new name is the same as current
      if (newName === oldRepoName) {
        window.alert("New project name is the same as the current name.");
        return null;
      }

      setRenameProgress(10);

      // Rename the GitHub repository
      try {
        await authorizedUserOcto.rest.repos.update({
          owner: currentUser,
          repo: oldRepoName,
          name: newName,
        });
      } catch (err) {
        console.error("Error renaming GitHub repository:", err);
        window.alert(
          "Error renaming repository on GitHub. The name might already be taken or invalid. Please try a different name.",
        );
        return null;
      }

      setRenameProgress(50);

      // Update project entry in AWS
      const updateKeysUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/update-project-keys";
      const updatedSearchField = (
        newName +
        " " +
        currentAWSnode.owner +
        " " +
        (currentAWSnode.description || "") +
        " " +
        currentAWSnode.topics?.join(" " || "")
      ).toLowerCase();

      const updateKeysResponse = await fetch(updateKeysUrl, {
        method: "POST",
        body: JSON.stringify({
          oldOwner: oldOwner,
          oldRepoName: oldRepoName,
          newOwner: currentAWSnode.owner,
          newRepoName: newName,
          searchField: updatedSearchField,
          html_url: `https://github.com/${currentAWSnode.owner}/${newName}`,
          readMe: `https://raw.githubusercontent.com/${currentAWSnode.owner}/${newName}/master/README.md?sanitize=true`,
          contentURL: `https://raw.githubusercontent.com/${currentAWSnode.owner}/${newName}/master/project.abundance?sanitize=true`,
          svgURL: `https://raw.githubusercontent.com/${currentAWSnode.owner}/${newName}/master/project.svg?sanitize=true`,
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });

      setRenameProgress(70);

      const updatedAWSnode = await updateKeysResponse.json();
      console.log("AWS update response:", updatedAWSnode);

      setRenameProgress(75);

      // Update the top molecule name in project.abundance to match the new project name
      try {
        // Get the current project.abundance file
        const projectFileResponse = await authorizedUserOcto.request(
          "GET /repos/{owner}/{repo}/contents/{path}",
          {
            owner: currentUser,
            repo: newName,
            path: "project.abundance",
          },
        );

        let projectFileContent;
        if (
          !projectFileResponse.data.content ||
          projectFileResponse.data.content.length === 0
        ) {
          // Handle large files using download_url
          const contentResponse = await fetch(
            projectFileResponse.data.download_url,
          );
          projectFileContent = await contentResponse.text();
        } else {
          // Decode base64 content
          projectFileContent = GlobalVariables.fromBinaryStr(
            atob(projectFileResponse.data.content),
          );
        }

        // Parse the JSON
        const projectData = JSON.parse(projectFileContent);

        // Update the top molecule name to match the new project name
        if (projectData && projectData.name) {
          projectData.name = newName;
        }

        // Convert back to base64
        const updatedContent = window.btoa(
          GlobalVariables.toBinaryStr(JSON.stringify(projectData, null, 4)),
        );

        // Update the file in the repo
        await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
          owner: currentUser,
          repo: newName,
          path: "project.abundance",
          message: `Update top molecule name to ${newName}`,
          content: updatedContent,
          sha: projectFileResponse.data.sha,
        });
      } catch (err) {
        console.error("Error updating top molecule name:", err);
        // Continue even if this fails - project is still functional
      }

      setRenameProgress(90);
      console.log("Project renamed successfully");
      // Update global variables
      GlobalVariables.currentAWSnode = updatedAWSnode;
      GlobalVariables.currentRepoName = newName;
      // Update the in-memory top molecule name to reflect the rename
      if (GlobalVariables.topLevelMolecule) {
        GlobalVariables.topLevelMolecule.name = newName;
      }
      /*if (GlobalVariables.currentRepo) {
          GlobalVariables.currentRepo.name = newName;
        }*/

      setRenameProgress(100);
      return updatedAWSnode;
    } catch (err) {
      console.error("Error renaming project:", err);
      window.alert(
        "An error occurred while renaming the project. Please try again.",
      );
      return null;
    }
  };

  /**
   * Validates if the current GitHub token is still valid
   */
  const validateGitHubToken = async (octokit) => {
    try {
      await octokit.request("GET /user");
      return true;
    } catch (error) {
      console.warn("GitHub token validation failed:", error.message);
      return false;
    }
  };

  /**
   * Handles authentication errors by redirecting to re-authentication
   */
  const handleAuthenticationError = (
    error,
    saveType,
    currentProjectRep,
    setErrorNotification,
  ) => {
    console.error("Authentication error during save:", error);

    // Show user-friendly error message
    if (setErrorNotification) {
      setErrorNotification(
        `Save failed due to expired login. You will be redirected to re-authenticate.`,
      );
      setTimeout(() => {
        setErrorNotification(null);
        authRedirectHandler({
          authType: "save",
          currentProjectRep,
          returnTo: `/${GlobalVariables.currentAWSnode.owner}/${GlobalVariables.currentAWSnode.repoName}`,
        });
      }, 2000);
    } else {
      authRedirectHandler({
        authType: "save",
        currentProjectRep,
        returnTo: `/${GlobalVariables.currentAWSnode.owner}/${GlobalVariables.currentAWSnode.repoName}`,
      });
    }
  };

  /**
   * Generate a thumbnail for the project
   */
  const generateProjectThumbnail = async (meshRef) => {
    //Generate a thumbnail for the project
    if (GlobalVariables.topLevelMolecule.value == null) {
      console.warn(
        "No top level molecule value found for thumbnail generation.",
      );
      return null;
    }

    // Check if meshRef and meshRef.current are available
    if (!meshRef || !meshRef.current) {
      console.warn("meshRef is not available for thumbnail generation.");
      return null;
    }

    return GlobalVariables.pool
      .proxy()
      .then((worker) => {
        return worker.generateDisplayMesh(
          GlobalVariables.topLevelMolecule.value,
          GlobalVariables.topLevelMolecule.getContext(),
        );
      })
      .then(async (m) => {
        const svg = await meshRef.current.buildThumbnail(m.mesh);
        console.log("Project thumbnail generated.");
        return svg;
      });
  };

  /**
   * Create a commit as part of the saving process.
   */
  const createCommit = async function (
    octokit,
    { owner, repo, base, changes },
    setSaveProgress,
    saveType = "Auto Save",
    setErrorNotification,
  ) {
    try {
      setSaveProgress(35);
      if (!base) {
        const repoResponse = await octokit.request(
          "GET /repos/{owner}/{repo}",
          {
            owner: owner,
            repo: repo,
          },
        );

        let htmlURL = repoResponse.data.html_url;
        const privateRepo = repoResponse.data.private;
        setSaveProgress(40);

        base = repoResponse.data.default_branch;

        const commitsResponse = await octokit.rest.repos.listCommits({
          owner,
          repo,
          sha: base,
          per_page: 1,
        });

        setSaveProgress(50);
        let latestCommitSha = commitsResponse.data[0].sha;
        const treeSha = commitsResponse.data[0].commit.tree.sha;

        const treeResponse = await octokit.rest.git.createTree({
          owner,
          repo,
          base_tree: treeSha,
          tree: Object.keys(changes.files).map((path) => {
            if (changes.files[path] != null) {
              return {
                path,
                mode: "100644",
                content: changes.files[path],
              };
            } else {
              return {
                path,
                mode: "100644",
                sha: null,
              };
            }
          }),
        });

        setSaveProgress(60);
        const newTreeSha = treeResponse.data.sha;

        const commitResponse = await octokit.rest.git.createCommit({
          owner,
          repo,
          message: changes.commit,
          tree: newTreeSha,
          parents: [latestCommitSha],
        });

        setSaveProgress(70);
        latestCommitSha = commitResponse.data.sha;

        await octokit.rest.git.updateRef({
          owner,
          repo,
          sha: latestCommitSha,
          ref: "heads/" + base,
          force: true,
        });

        setSaveProgress(80);

        const githubMoleculeUsedList = await searchGithubMolecules(
          GlobalVariables.topLevelMolecule,
        );

        /*aws dynamo update-item lambda, also updates dateModified on aws side*/
        const apiUpdateUrl =
          "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/update-item";
        let topicString = GlobalVariables.currentAWSnode.topics.join(" ");
        let searchField = (
          repo +
          " " +
          owner +
          " " +
          GlobalVariables.currentAWSnode.description +
          " " +
          topicString
        ).toLowerCase();

        await fetch(apiUpdateUrl, {
          method: "POST",
          body: JSON.stringify({
            owner: owner,
            repoName: repo,
            attributeUpdates: {
              ranking: 0,
              privateRepo: privateRepo,
              html_url: htmlURL,
              searchField: searchField,
              githubMoleculesUsed: githubMoleculeUsedList,
              description: GlobalVariables.currentAWSnode.description,
              topics: GlobalVariables.currentAWSnode.topics,
            },
          }),
          headers: {
            "Content-type": "application/json; charset=UTF-8",
          },
        });

        console.warn("Project saved on git and aws updated");
      }
    } catch (error) {
      console.error("Error during commit creation:", error);

      // Check if this is an authentication error
      if (error.status === 401 || error.message.includes("Bad credentials")) {
        handleAuthenticationError(error, saveType, null, setErrorNotification);
      } else {
        // Handle other errors
        if (setErrorNotification) {
          setErrorNotification(
            `Save failed: ${error.message || "Unknown error occurred"}`,
          );
          setTimeout(() => setErrorNotification(null), 5000);
        }
        setSaveProgress(0); // Reset save progress
      }

      throw error; // Re-throw to let calling function handle it
    }
  };

  /**
   * Saves project by making a commit to the Github repository.
   * @param {Function} setSaveProgress - Function to update save progress
   * @param {string} typeSave - Type of save operation
   * @param {boolean} forceSave - If true, bypasses the "no changes" check
   * @param {object} meshRef - Reference to the mesh for thumbnail generation (optional)
   * @param {Function} setErrorNotification - Function to set error notifications (optional)
   */
  const saveProject = async (
    setSaveProgress,
    typeSave,
    forceSave = false,
    meshRef = null,
    setErrorNotification = null,
  ) => {
    try {
      //We only want to save if something has actually changed since the last save
      var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize();

      //Don't save again if nothing has changed (unless forceSave is true)
      if (
        !forceSave &&
        JSON.stringify(jsonRepOfProject) == JSON.stringify(lastSaveData.current)
      ) {
        return;
      }

      // First validate the GitHub token
      if (authorizedUserOcto) {
        const isTokenValid = await validateGitHubToken(authorizedUserOcto);
        if (!isTokenValid) {
          handleAuthenticationError(
            new Error("GitHub token has expired"),
            typeSave,
            JSON.stringify(jsonRepOfProject),
            setErrorNotification,
          );
          return;
        }
      }

      lastSaveData.current = jsonRepOfProject; //Save the data so we can compare it next time

      setSaveProgress(5); //Set the state to 5% to show the progress bar

      let finalSVG;
      // Only generate thumbnail for user-triggered saves, not auto saves
      if (typeSave !== "Auto Save" && meshRef) {
        finalSVG = await generateProjectThumbnail(meshRef).catch((error) => {
          console.error("Error generating final project thumbnail: ", error);
        });
      }

      setSaveProgress(10);
      // Reuse the already serialized project data instead of serializing again
      jsonRepOfProject.filetypeVersion = 1;
      const projectContent = JSON.stringify(jsonRepOfProject, null, 2);
      // format and compile the BOM
      let bomContent = GlobalVariables.topLevelMolecule.formatBom();
      var readmeHeader =
        "###### Note: Do not edit this file directly, it is automatically generated from the CAD model";

      var readmeContent =
        readmeHeader +
        "\n\n" +
        "# " +
        GlobalVariables.currentAWSnode.repoName +
        "\n\n![](/project.svg)\n\n";

      setSaveProgress(20);

      let readMeRequestResult =
        await GlobalVariables.topLevelMolecule.requestReadme();

      let readMeTextArray = " ";

      readMeRequestResult.forEach((item) => {
        readMeTextArray = readMeTextArray.concat(item["readMeText"]) + "\n\n";
      });
      readmeContent = readmeContent + "\n\n" + readMeTextArray + "\n\n";

      /** File object to commit */
      let filesObject = {
        "BillOfMaterials.md": bomContent,
        "README.md": readmeContent,
        "project.abundance": projectContent,
      };

      /* add any new SVGs to the project change files*/
      const readmeSVGs = readMeRequestResult;
      let backupProjectSVG;
      if (readmeSVGs) {
        readmeSVGs.forEach((item) => {
          if (item.svg != null) {
            filesObject["readme" + item.uniqueID + ".svg"] = item.svg;
            backupProjectSVG = item.svg;
          }
        });
      }

      // Helper function to check if an SVG is valid and has content
      const isValidSVG = (svg) => {
        if (!svg) return false;
        // Check if SVG is empty (has no paths or other content between svg tags)
        // An empty SVG looks like: <svg viewBox="..." xmlns="..."></svg>
        const hasContent =
          svg.includes("<path") ||
          svg.includes("<circle") ||
          svg.includes("<rect") ||
          svg.includes("<line") ||
          svg.includes("<polygon") ||
          svg.includes("<polyline");
        return hasContent;
      };

      // Only update project thumbnail if a valid one has been generated
      // Prioritize finalSVG from main output, but fall back to readme SVG if main output is empty
      const thumbnailToUse =
        finalSVG && isValidSVG(finalSVG)
          ? finalSVG
          : backupProjectSVG && isValidSVG(backupProjectSVG)
            ? backupProjectSVG
            : null;
      if (thumbnailToUse) {
        filesObject["project.svg"] = thumbnailToUse;
      }
      // If no valid thumbnail was generated, don't include project.svg in the commit
      // This preserves the existing thumbnail in the repository

      setSaveProgress(30);

      await createCommit(
        authorizedUserOcto,
        {
          owner: GlobalVariables.currentUser,
          repo: GlobalVariables.currentAWSnode.repoName,
          changes: {
            files: filesObject,
            commit: typeSave ? typeSave : "Auto Save",
          },
        },
        setSaveProgress,
        typeSave,
        setErrorNotification,
      );

      if (typeSave !== "Auto Save") {
        const geomIds = GlobalVariables.topLevelMolecule.deepGeomList();
        // Sweep is best-effort and can take a long time (up to a minute). Don't await, just let it run
        // in the background and mark save as completed.
        GlobalVariables.cad
          .sweepCache(geomIds, GlobalVariables.topLevelMolecule.getContext())
          .then((count) => {
            console.log("cache sweep complete, removed: " + count + " items");
          })
          .catch((error) => {
            console.error("Error during cache sweep:", error);
          });
      }

      setSaveProgress(100);
    } catch (error) {
      console.error("Error during project save:", error);
      // The createCommit function already handles authentication errors,
      // so we only need to handle other types of errors here
      if (!error.message.includes("Bad credentials") && error.status !== 401) {
        setNotification(
          `Save failed: ${error.message || "Unknown error occurred"}`,
          "error",
        );
        setTimeout(() => setNotification(null), 5000);
      }

      setSaveProgress(0); // Reset save progress
    }
  };

  const value = {
    size,
    setSize,
    cad,
    loadProject,
    createProject,
    duplicateProject,
    forkProject,
    renameProject,
    searchGithubMolecules,
    saveProject,
  };
  return (
    <ProjectContext.Provider value={value}>{children}</ProjectContext.Provider>
  );
}

/**
 * Hook to use the ProjectContext
 */
export function useProject() {
  const context = useContext(ProjectContext);
  if (!context) {
    throw new Error("useProject must be used within a ProjectProvider");
  }
  return context;
}
