import React, { createContext, useContext, useState } from "react";
import GlobalVariables from "../js/globalvariables.js";
import Molecule from "../molecules/molecule.js";
import { licenses } from "../js/licenseOptions.js";
import { re } from "mathjs";

const ProjectContext = createContext();

/**
 * Context provider for project-level operations and state.
 * Centralizes project loading, saving, and CAD operations.
 */
export function ProjectProvider({ children, cad, loadProject }) {
  const [size, setSize] = useState(5);

  /**
   * The text to display at the top of the bill of materials.
   * @type {string}
   */
  var bomHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model \n# Bill Of Materials \n |Part|Number Needed|Price|Source| \n |----|----------|-----|-----|";
  /**
   * The text to display at the top of the ReadMe file.
   * @type {string}
   */
  var readmeHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model";

  /**
   * Create a new project or exports current molecule to github and navigate to new project create page
   * * @param {string} name - Project Name
   * @param {array} topics - Array of topics
   * @param {string} description - Project Description
   * @param {object} molecule - If there's an existing molecule to export
   * @param {boolean} exporting - If exporting a molecule
   *
   */
  const createProject = async (
    authorizedUserOcto,
    [name, topics, description, license, units],
    molecule,
    exporting,
    setNewProjectBar
  ) => {
    if (molecule !== undefined && exporting) {
      GlobalVariables.topLevelMolecule = molecule;
      molecule.topLevel = true;
    } else {
      GlobalVariables.topLevelMolecule = new Molecule({
        x: 0,
        y: 0,
        topLevel: true,
        name: name,
        atomType: "Molecule",
        uniqueID: GlobalVariables.generateUniqueID(),
        unitsKey: units,
      });
    }
    GlobalVariables.currentMolecule = GlobalVariables.topLevelMolecule;

    // Create the repo
    let result;
    try {
      result = await authorizedUserOcto.request("POST /user/repos", {
        name: name,
        description: description,
        headers: {
          "X-GitHub-Api-Version": "2022-11-28",
        },
      });
    } catch (err) {
      window.alert(
        "Error creating project. That name might be taken already. Please try again with a different name."
      );
      return null;
    }
    setNewProjectBar(10);
    let currentRepoName = result.data.name;
    let currentUser = GlobalVariables.currentUser;

    var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize();
    jsonRepOfProject.filetypeVersion = 1;
    const projectContent = window.btoa(
      GlobalVariables.toBinaryStr(JSON.stringify(jsonRepOfProject, null, 4))
    );
    let topicString = topics.join(" ");
    let searchField = (
      result.data.name +
      " " +
      result.data.owner.login +
      " " +
      description +
      " " +
      topicString
    ).toLowerCase();
    let newProjectBody = {
      owner: result.data.owner.login,
      description: description,
      ranking: result.data.stargazers_count,
      searchField: searchField,
      repoName: result.data.name,
      forks: result.data.forks_count,
      topMoleculeID: GlobalVariables.topLevelMolecule.uniqueID,
      topics: topics,
      html_url: result.data.html_url,
      parentRepo: null,
      readme:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/README.md?sanitize=true",
      contentURL:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/project.abundance?sanitize=true",
      githubMoleculesUsed: [],
      svgURL:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/project.svg?sanitize=true",
      dateCreated: result.data.created_at,
    };

    // Post new project to AWS database
    const apiUrl =
      "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage//post-new-project";
    await fetch(apiUrl, {
      method: "POST",
      body: JSON.stringify(newProjectBody),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });
    GlobalVariables.currentAWSnode = newProjectBody;

    // Add to user table
    const apiUpdateUserUrl =
      "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/USER-TABLE";
    await fetch(apiUpdateUserUrl, {
      method: "POST",
      body: JSON.stringify({
        user: GlobalVariables.currentUser,
        attributeUpdates: { numProjectsOwned: 1 },
        updateType: "SET",
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });

    // Create the project files sequentially
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "project.abundance",
      message: "Initialize repo",
      content: projectContent,
    });
    setNewProjectBar(20);

    let content = window.btoa(bomHeader);
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "BillOfMaterials.md",
      message: "initialize BOM",
      content: content,
    });
    setNewProjectBar(30);

    content = window.btoa(readmeHeader);
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "README.md",
      message: "initialize README",
      content: content,
    });
    setNewProjectBar(40);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "project.svg",
      message: "SVG Picture",
      content: "",
    });
    setNewProjectBar(50);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: ".gitattributes",
      message: "Create gitattributes",
      content: window.btoa("data binary"),
    });
    setNewProjectBar(60);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "data.json",
      message: "Data file",
      content: "",
    });
    setNewProjectBar(80);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "LICENSE.txt",
      message: "Establish license",
      content: window.btoa(GlobalVariables.toBinaryStr(licenses[license])),
    });
    setNewProjectBar(90);

    await authorizedUserOcto.rest.repos.replaceAllTopics({
      owner: currentUser,
      repo: currentRepoName,
      names: topics,
    });

    // All done, return the AWS node
    console.log("Project created");
    console.log(GlobalVariables.currentAWSnode);
    return GlobalVariables.currentAWSnode;
  };

  const value = {
    size,
    setSize,
    cad,
    loadProject,
    createProject,
  };
  return (
    <ProjectContext.Provider value={value}>{children}</ProjectContext.Provider>
  );
}

/**
 * Hook to use the ProjectContext
 */
export function useProject() {
  const context = useContext(ProjectContext);
  if (!context) {
    throw new Error("useProject must be used within a ProjectProvider");
  }
  return context;
}
