import React, { createContext, useContext, useState } from "react";
import GlobalVariables from "../js/globalvariables.js";
import Molecule from "../molecules/molecule.js";
import { licenses } from "../js/licenseOptions.js";
import { re } from "mathjs";

const ProjectContext = createContext();

/**
 * Context provider for project-level operations and state.
 * Centralizes project loading, saving, and CAD operations.
 */
export function ProjectProvider({ children, cad, loadProject }) {
  const [size, setSize] = useState(5);

  /**
   * The text to display at the top of the bill of materials.
   * @type {string}
   */
  var bomHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model \n# Bill Of Materials \n |Part|Number Needed|Price|Source| \n |----|----------|-----|-----|";
  /**
   * The text to display at the top of the ReadMe file.
   * @type {string}
   */
  var readmeHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model";

  /**
   * Create a new project or exports current molecule to github and navigate to new project create page
   * * @param {string} name - Project Name
   * @param {array} topics - Array of topics
   * @param {string} description - Project Description
   * @param {object} molecule - If there's an existing molecule to export
   * @param {boolean} exporting - If exporting a molecule
   *
   */
  const createProject = async (
    authorizedUserOcto,
    [name, topics, description, license, units],
    molecule,
    exporting,
    setNewProjectBar
  ) => {
    if (molecule !== undefined && exporting) {
      GlobalVariables.topLevelMolecule = molecule;
      molecule.topLevel = true;
    } else {
      GlobalVariables.topLevelMolecule = new Molecule({
        x: 0,
        y: 0,
        topLevel: true,
        name: name,
        atomType: "Molecule",
        uniqueID: GlobalVariables.generateUniqueID(),
        unitsKey: units,
      });
    }
    GlobalVariables.currentMolecule = GlobalVariables.topLevelMolecule;

    // Create the repo
    let result;
    let errors = [];
    try {
      result = await authorizedUserOcto.request("POST /user/repos", {
        name: name,
        description: description,
        headers: {
          "X-GitHub-Api-Version": "2022-11-28",
        },
      });
    } catch (err) {
      window.alert(
        "Error creating project. That name might be taken already. Please try again with a different name."
      );
      return null;
    }
    setNewProjectBar(10);
    let currentRepoName = result.data.name;
    let currentUser = GlobalVariables.currentUser;

    // Check if the repo name was changed by GitHub
    if (currentRepoName !== name) {
      errors.push(
        `Project name was changed from "${name}" to "${currentRepoName}" to comply with GitHub requirements.`
      );
    }

    var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize();
    jsonRepOfProject.filetypeVersion = 1;
    const projectContent = window.btoa(
      GlobalVariables.toBinaryStr(JSON.stringify(jsonRepOfProject, null, 4))
    );
    let topicString = topics.join(" ");
    let searchField = (
      result.data.name +
      " " +
      result.data.owner.login +
      " " +
      description +
      " " +
      topicString
    ).toLowerCase();
    let newProjectBody = {
      owner: result.data.owner.login,
      description: description,
      ranking: result.data.stargazers_count,
      searchField: searchField,
      repoName: result.data.name,
      forks: result.data.forks_count,
      topMoleculeID: GlobalVariables.topLevelMolecule.uniqueID,
      topics: topics,
      html_url: result.data.html_url,
      parentRepo: null,
      readme:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/README.md?sanitize=true",
      contentURL:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/project.abundance?sanitize=true",
      githubMoleculesUsed: [],
      svgURL:
        "https://raw.githubusercontent.com/" +
        result.data.full_name +
        "/master/project.svg?sanitize=true",
      dateCreated: result.data.created_at,
    };

    // Post new project to AWS database
    const apiUrl =
      "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage//post-new-project";
    await fetch(apiUrl, {
      method: "POST",
      body: JSON.stringify(newProjectBody),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });
    GlobalVariables.currentAWSnode = newProjectBody;

    // Add to user table
    const apiUpdateUserUrl =
      "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/USER-TABLE";
    await fetch(apiUpdateUserUrl, {
      method: "POST",
      body: JSON.stringify({
        user: GlobalVariables.currentUser,
        attributeUpdates: { numProjectsOwned: 1 },
        updateType: "SET",
      }),
      headers: {
        "Content-type": "application/json; charset=UTF-8",
      },
    });

    // Create the project files sequentially
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "project.abundance",
      message: "Initialize repo",
      content: projectContent,
    });
    setNewProjectBar(20);

    let content = window.btoa(bomHeader);
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "BillOfMaterials.md",
      message: "initialize BOM",
      content: content,
    });
    setNewProjectBar(30);

    content = window.btoa(readmeHeader);
    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "README.md",
      message: "initialize README",
      content: content,
    });
    setNewProjectBar(40);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "project.svg",
      message: "SVG Picture",
      content: "",
    });
    setNewProjectBar(50);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: ".gitattributes",
      message: "Create gitattributes",
      content: window.btoa("data binary"),
    });
    setNewProjectBar(60);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "data.json",
      message: "Data file",
      content: "",
    });
    setNewProjectBar(80);

    await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
      owner: currentUser,
      repo: currentRepoName,
      path: "LICENSE.txt",
      message: "Establish license",
      content: window.btoa(GlobalVariables.toBinaryStr(licenses[license])),
    });
    setNewProjectBar(90);

    // Set topics with error handling
    try {
      await authorizedUserOcto.rest.repos.replaceAllTopics({
        owner: currentUser,
        repo: currentRepoName,
        names: topics,
      });
    } catch (err) {
      console.error("Error setting topics:", err);
      errors.push(
        "Some project tags could not be added. GitHub requires tags to be lowercase, contain only letters, numbers, and hyphens, and be 50 characters or less."
      );
    }

    // Display any errors or warnings to the user
    if (errors.length > 0) {
      window.alert(
        "Project created successfully!\n\nNote:\n" + errors.join("\n")
      );
    }

    // All done, return the AWS node
    console.log("Project created");
    console.log(GlobalVariables.currentAWSnode);
    return GlobalVariables.currentAWSnode;
  };

  /**
   * Duplicate the current project by creating a new repository
   * @param {object} authorizedUserOcto - Authenticated Octokit instance
   * @param {function} setDuplicateProjectBar - Progress bar callback
   * @param {string} customName - Custom name for the duplicated project (optional)
   * @returns {object} The new project AWS node or null on error
   */
  const duplicateProject = async (
    authorizedUserOcto,
    setDuplicateProjectBar,
    customName = null
  ) => {
    console.log("Duplicating project...");
    console.log(GlobalVariables.currentRepo);
    try {
      const currentRepo = GlobalVariables.currentRepo;
      const currentUser = GlobalVariables.currentUser;

      if (!currentRepo || !currentUser) {
        window.alert(
          "Cannot duplicate project: No active project or user not authenticated."
        );
        return null;
      }

      // Use custom name or generate new project name with "-copy" suffix
      let newRepoName = customName || currentRepo.name + "-copy";

      // Check if name already exists and increment if needed (only if using default name)
      if (!customName) {
        let nameExists = true;
        let counter = 1;
        while (nameExists) {
          try {
            await authorizedUserOcto.request("GET /repos/{owner}/{repo}", {
              owner: currentUser,
              repo: newRepoName,
            });
            // If we get here, repo exists, so try with a counter
            newRepoName = currentRepo.name + "-copy-" + counter;
            counter++;
          } catch (err) {
            // 404 means repo doesn't exist, so we can use this name
            if (err.status === 404) {
              nameExists = false;
            } else {
              throw err;
            }
          }
        }
      }

      setDuplicateProjectBar(5);

      // Create the new repository
      let newRepo;
      try {
        newRepo = await authorizedUserOcto.request("POST /user/repos", {
          name: newRepoName,
          description: currentRepo.description || "",
          headers: {
            "X-GitHub-Api-Version": "2022-11-28",
          },
        });
      } catch (err) {
        window.alert("Error creating duplicate project. Please try again.");
        return null;
      }

      setDuplicateProjectBar(10);

      // Get all files from the current repository
      const filesToCopy = [
        "project.abundance",
        "BillOfMaterials.md",
        "README.md",
        "project.svg",
        ".gitattributes",
        "data.json",
        "LICENSE.txt",
      ];

      let copiedFiles = 0;
      const totalFiles = filesToCopy.length;

      // Copy each file from the original repo to the new repo
      for (const filePath of filesToCopy) {
        try {
          // Get file content from current repo
          const fileResponse = await authorizedUserOcto.request(
            "GET /repos/{owner}/{repo}/contents/{path}",
            {
              owner: currentRepo.owner.login,
              repo: currentRepo.name,
              path: filePath,
            }
          );

          let fileContent;
          if (
            !fileResponse.data.content ||
            fileResponse.data.content.length === 0
          ) {
            // Handle large files using download_url
            const contentResponse = await fetch(fileResponse.data.download_url);
            const rawContent = await contentResponse.text();
            fileContent = window.btoa(GlobalVariables.toBinaryStr(rawContent));
          } else {
            // Use the base64 content directly
            fileContent = fileResponse.data.content.replace(/\n/g, "");
          }

          // Create file in new repo
          await authorizedUserOcto.rest.repos.createOrUpdateFileContents({
            owner: currentUser,
            repo: newRepo.data.name,
            path: filePath,
            message: `Copy ${filePath} from ${currentRepo.name}`,
            content: fileContent,
          });

          copiedFiles++;
          const progress = 10 + Math.floor((copiedFiles / totalFiles) * 70);
          setDuplicateProjectBar(progress);
        } catch (err) {
          console.error(`Error copying file ${filePath}:`, err);
          // Continue with other files even if one fails
        }
      }

      setDuplicateProjectBar(85);

      // Copy topics if they exist
      if (currentRepo.topics && currentRepo.topics.length > 0) {
        try {
          await authorizedUserOcto.rest.repos.replaceAllTopics({
            owner: currentUser,
            repo: newRepo.data.name,
            names: currentRepo.topics,
          });
        } catch (err) {
          console.error("Error copying topics:", err);
        }
      }

      setDuplicateProjectBar(95);

      // Create AWS node for the new project
      const newProjectBody = {
        owner: currentUser,
        description: newRepo.data.description || "",
        ranking: 0,
        searchField: (
          newRepo.data.name +
          " " +
          currentUser +
          " " +
          (newRepo.data.description || "")
        ).toLowerCase(),
        repoName: newRepo.data.name,
        forks: 0,
        topMoleculeID: GlobalVariables.topLevelMolecule?.uniqueID || "",
        topics: currentRepo.topics || [],
        html_url: newRepo.data.html_url,
        parentRepo: null,
        readme:
          "https://raw.githubusercontent.com/" +
          newRepo.data.full_name +
          "/master/README.md?sanitize=true",
        contentURL:
          "https://raw.githubusercontent.com/" +
          newRepo.data.full_name +
          "/master/project.abundance?sanitize=true",
        githubMoleculesUsed: [],
        svgURL:
          "https://raw.githubusercontent.com/" +
          newRepo.data.full_name +
          "/master/project.svg?sanitize=true",
        dateCreated: newRepo.data.created_at,
      };

      // Post new project to AWS database
      const apiUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/post-new-project";
      const postProjectResponse = await fetch(apiUrl, {
        method: "POST",
        body: JSON.stringify(newProjectBody),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });
      console.log("Posted new project to AWS:", postProjectResponse);
      if (postProjectResponse.status !== 200) {
        throw new Error(
          `Failed to post new project: ${postProjectResponse.status}`
        );
      }

      // Update user table
      const apiUpdateUserUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/USER-TABLE";
      const updateUserResponse = await fetch(apiUpdateUserUrl, {
        method: "POST",
        body: JSON.stringify({
          user: currentUser,
          attributeUpdates: { numProjectsOwned: 1 },
          updateType: "SET",
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });
      if (!updateUserResponse.ok) {
        throw new Error(
          `Failed to update user table: ${updateUserResponse.status}`
        );
      }

      setDuplicateProjectBar(100);

      return newProjectBody;
    } catch (err) {
      console.error("Error duplicating project:", err);
      window.alert(
        "An error occurred while duplicating the project. Please try again."
      );
      return null;
    }
  };

  /**
   * Rename an existing project by updating GitHub repository and AWS entry
   * @param {object} authorizedUserOcto - Authenticated Octokit instance
   * @param {string} newName - New name for the project
   * @param {function} setRenameProgress - Progress callback (0-100)
   * @returns {object|null} Updated AWS node or null on error
   */
  const renameProject = async (
    authorizedUserOcto,
    newName,
    setRenameProgress = () => {}
  ) => {
    console.log(GlobalVariables.currentRepo);
    try {
      const currentUser = GlobalVariables.currentUser;
      const currentAWSnode = GlobalVariables.currentAWSnode;
      const oldRepoName = currentAWSnode.repoName;
      const oldOwner = currentAWSnode.owner;

      if (!authorizedUserOcto || !currentUser) {
        window.alert("Missing required data for renaming project.");
        return null;
      }

      // Check if new name is the same as current
      if (newName === oldRepoName) {
        window.alert("New project name is the same as the current name.");
        return null;
      }

      setRenameProgress(10);

      // Rename the GitHub repository
      try {
        await authorizedUserOcto.rest.repos.update({
          owner: currentUser,
          repo: oldRepoName,
          name: newName,
        });
      } catch (err) {
        console.error("Error renaming GitHub repository:", err);
        window.alert(
          "Error renaming repository on GitHub. The name might already be taken or invalid. Please try a different name."
        );
        return null;
      }

      setRenameProgress(50);

      // Update project entry in AWS
      const updateKeysUrl =
        "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/update-project-keys";
      const updatedSearchField = (
        newName +
        " " +
        currentAWSnode.owner +
        " " +
        (currentAWSnode.description || "") +
        " " +
        currentAWSnode.topics?.join(" " || "")
      ).toLowerCase();

      const updateKeysResponse = await fetch(updateKeysUrl, {
        method: "POST",
        body: JSON.stringify({
          oldOwner: oldOwner,
          oldRepoName: oldRepoName,
          newOwner: currentAWSnode.owner,
          newRepoName: newName,
          searchField: updatedSearchField,
          html_url: `https://github.com/${currentAWSnode.owner}/${newName}`,
          readMe: `https://raw.githubusercontent.com/${currentAWSnode.owner}/${newName}/master/README.md?sanitize=true`,
          contentURL: `https://raw.githubusercontent.com/${currentAWSnode.owner}/${newName}/master/project.abundance?sanitize=true`,
          svgURL: `https://raw.githubusercontent.com/${currentAWSnode.owner}/${newName}/master/project.svg?sanitize=true`,
        }),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });

      setRenameProgress(70);

      const updatedAWSnode = await updateKeysResponse.json();
      console.log("AWS update response:", updatedAWSnode);

      setRenameProgress(90);
      console.log("Project renamed successfully");
      // Update global variables
      GlobalVariables.currentAWSnode = updatedAWSnode;
      GlobalVariables.currentRepoName = newName;
      /*if (GlobalVariables.currentRepo) {
          GlobalVariables.currentRepo.name = newName;
        }*/

      setRenameProgress(100);
      return updatedAWSnode;
    } catch (err) {
      console.error("Error renaming project:", err);
      window.alert(
        "An error occurred while renaming the project. Please try again."
      );
      return null;
    }
  };

  const value = {
    size,
    setSize,
    cad,
    loadProject,
    createProject,
    duplicateProject,
    renameProject,
  };
  return (
    <ProjectContext.Provider value={value}>{children}</ProjectContext.Provider>
  );
}

/**
 * Hook to use the ProjectContext
 */
export function useProject() {
  const context = useContext(ProjectContext);
  if (!context) {
    throw new Error("useProject must be used within a ProjectProvider");
  }
  return context;
}
