// Test generated by create-code-atom skill
import { init } from "../src/worker/util.ts";
import { executeCode } from "../src/worker/code.ts";
import { rectangle } from "../src/worker/shapes.ts";
import { extrude } from "../src/worker/actions.ts";

const context = { project: "test-code-atom" };

describe("fillet vertical edges code atom", () => {
  beforeAll(async () => {
    await init();
  });

  it("fillets only vertical (Z-axis) edges", async () => {
    const rect = await rectangle(10, 5, context);
    const testGeom = await extrude(rect, 8, context);

    const codeString = `
const Inputs = [
  { inputName: "shape", type: "geometry", defaultValue: null },
  { inputName: "radius", type: "number", defaultValue: 1 },
];

return await FilletInDirection(shape, radius, "Z");
    `;
    const args = { shape: testGeom, radius: 1 };
    const result = await executeCode(codeString, args, context);
    expect(result).toBeDefined();
    expect(result.geometry).toBeDefined();
  });
});

describe("ai-generated code atom", () => {
  beforeAll(async () => {
    await init();
  });

  it("cylinder - creates geometry from scratch", async () => {
    const codeString = `
      const Inputs = [
        { inputName: "diameter", type: "number", defaultValue: 20 },
        { inputName: "height", type: "number", defaultValue: 30 },
      ];

      let solid = replicad.drawCircle(diameter / 2).sketchOnPlane().extrude(height);
      // Raw replicad shapes must be wrapped in an abundance object
      return {
        geometry: [solid],
        dimension: "3D",
        tags: [],
        color: "#aad7f2",
        plane: null,
        bom: []
      };
    `;

    const result = await executeCode(codeString, { diameter: 20, height: 30 }, context);
    expect(result).toBeDefined();
    expect(result.geometry).toBeDefined();
  });

  it("tube - boolean cut using native replicad methods", async () => {
    const codeString = `
      const Inputs = [
        { inputName: "outerDiameter", type: "number", defaultValue: 20 },
        { inputName: "wallThickness", type: "number", defaultValue: 2 },
        { inputName: "height", type: "number", defaultValue: 30 },
      ];

      let outerRadius = outerDiameter / 2;
      let innerRadius = outerRadius - wallThickness;

      let outer = replicad.drawCircle(outerRadius).sketchOnPlane().extrude(height);
      let inner = replicad.drawCircle(innerRadius).sketchOnPlane().extrude(height);
      // Use native replicad .cut() for shapes created inside the code atom
      let tube = outer.cut(inner);
      return {
        geometry: [tube],
        dimension: "3D",
        tags: [],
        color: "#aad7f2",
        plane: null,
        bom: []
      };
    `;

    const result = await executeCode(
      codeString,
      { outerDiameter: 20, wallThickness: 2, height: 30 },
      context
    );
    expect(result).toBeDefined();
    expect(result.geometry).toBeDefined();
  });

  it("linear pattern - uses Assembly/Move for geometry input from another atom", async () => {
    // Create test geometry (simulates geometry arriving from another atom)
    const rect = await rectangle(10, 5, context);
    const box = await extrude(rect, 8, context);

    const codeString = `
      const Inputs = [
        { inputName: "shape", type: "geometry", defaultValue: null },
        { inputName: "count", type: "number", defaultValue: 3 },
        { inputName: "spacing", type: "number", defaultValue: 20 },
      ];

      let shapes = [];
      for (let i = 0; i < count; i++) {
        shapes.push(await Move(shape, spacing * i, 0, 0));
      }
      return await Assembly(shapes);
    `;

    const result = await executeCode(
      codeString,
      { shape: box, count: 3, spacing: 20 },
      context
    );
    expect(result).toBeDefined();
    expect(result.geometry).toBeDefined();
  });
});
